In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import warnings

warnings.filterwarnings("ignore")

In [5]:
df = pd.read_csv("C:/Office 2019/DS_PW/DL_Practice/Shoppers Purchasing Intention/dataset/online_shoppers_intention.csv")
df

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,Feb,3,3,1,4,Returning_Visitor,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,Dec,4,6,1,1,Returning_Visitor,True,False
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,Nov,3,2,1,8,Returning_Visitor,True,False
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,Nov,3,2,1,13,Returning_Visitor,True,False
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,Nov,2,2,3,11,Returning_Visitor,False,False
12329,0,0.0,0,0.0,3,21.250000,0.000000,0.066667,0.000000,0.0,Nov,3,2,1,2,New_Visitor,True,False

In [6]:
df.drop("Month", axis=1, inplace=True)

In [7]:
X = df.drop("Revenue", axis=1)
y = df["Revenue"]

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
from sklearn.preprocessing import LabelEncoder

labelEncoder = LabelEncoder()
X_train['VisitorType'] = labelEncoder.fit_transform(X_train['VisitorType'])
X_test['VisitorType'] = labelEncoder.transform(X_test['VisitorType'])
print("visitor",labelEncoder.classes_)
X_train["Weekend"] = labelEncoder.fit_transform(X_train["Weekend"])
X_test["Weekend"] = labelEncoder.transform(X_test["Weekend"])
print("weekend",labelEncoder.classes_)
y_train = labelEncoder.fit_transform(y_train)
y_test = labelEncoder.transform(y_test)
print("purchased",labelEncoder.classes_)

visitor ['New_Visitor' 'Other' 'Returning_Visitor']
weekend [False  True]
purchased [False  True]

In [11]:
X_train.columns

Index(['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay',
       'OperatingSystems', 'Browser', 'Region', 'TrafficType', 'VisitorType',
       'Weekend'],
      dtype='object')

In [13]:
X_train.describe().T

,count,mean,std,min,25%,50%,75%,max
Administrative,9864.0,2.302818,3.297117,0.0,0.000000,1.000000,4.000000,27.000000
Administrative_Duration,9864.0,81.107226,177.511054,0.0,0.000000,8.000000,92.000000,3398.750000
Informational,9864.0,0.503447,1.266877,0.0,0.000000,0.000000,0.000000,24.000000
Informational_Duration,9864.0,34.062159,138.941112,0.0,0.000000,0.000000,0.000000,2549.375000
ProductRelated,9864.0,31.736922,44.562956,0.0,7.000000,18.000000,37.000000,705.000000
ProductRelated_Duration,9864.0,1197.331019,1922.835536,0.0,186.000000,602.541667,1471.189584,63973.522230
BounceRates,9864.0,0.021659,0.047469,0.0,0.000000,0.002961,0.016667,0.200000
ExitRates,9864.0,0.042613,0.047839,0.0,0.014286,0.025000,0.050000,0.200000
PageValues,9864.0,5.832987,18.483546,0.0,0.000000,0.000000,0.000000,361.763742
SpecialDay,9864.0,0.061071,0.198057,0.0,0.000000,0.000000,0.000000,1.000000
OperatingSystems,9864.0,2.121046,0.910107,1.0,2.000000,2.000000,3.000000,8.000000
Browser,9864.0,2.359692,1.723978,1.0,2.000000,2.000000,2.000000,13.000000
Region,9864.0,3.154501,2.412381,1.0,1.000000,3.000000,4.000000,9.000000
TrafficType,9864.0,4.073905,4.033786,1.0,2.000000,2.000000,4.000000,20.000000
VisitorType,9864.0,1.718674,0.689893,0.0,2.000000,2.000000,2.000000,2.000000
Weekend,9864.0,0.227899,0.419499,0.0,0.000000,0.000000,0.000000,1.000000

In [3]:
print(hj cfbhjbngfvr)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2246861293.py, line 1)

In [10]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1789829989.813875   11840 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1789829989.934532   11840 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1789829992.243886   11840 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

In [11]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((9864, 16), (2466, 16), (9864,), (2466,))

In [12]:
model = Sequential([
    Dense(16, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])

I0000 00:00:1789829993.681616   11840 gpu_device.cc:2043] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1763 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2050, pci bus id: 0000:01:00.0, compute capability: 8.6

In [13]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [18]:
model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.2)
joblib.dump(model, '/mnt/c/Office 2019/DS_PW/DL_Practice/Shoppers Purchasing Intention/Notebook/shoppers_model.pkl')

Epoch 1/50

I0000 00:00:1789830181.569240   12146 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_1336__.9

238/247 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8615 - loss: 0.7847

I0000 00:00:1789830183.810990   12143 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_1336__.9

247/247 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - accuracy: 0.8629 - loss: 0.7749 - val_accuracy: 0.8925 - val_loss: 0.4707
Epoch 2/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8593 - loss: 0.7109 - val_accuracy: 0.8728 - val_loss: 0.5207
Epoch 3/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8525 - loss: 0.9707 - val_accuracy: 0.8753 - val_loss: 0.4630
Epoch 4/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8605 - loss: 0.9205 - val_accuracy: 0.8834 - val_loss: 0.9964
Epoch 5/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8693 - loss: 0.6893 - val_accuracy: 0.8844 - val_loss: 0.5489
Epoch 6/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8606 - loss: 1.2440 - val_accuracy: 0.8900 - val_loss: 0.3983
Epoch 7/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8662 - loss: 0.5137 - val_accuracy: 0.8870 - val_loss: 0.3764
Epoch 8/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8695 - loss: 0.6624 - val_accuracy: 0.8718 - val_loss: 0.4385
Epoch 9/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8763 - loss: 0.5306 - val_accuracy: 0.8287 - val_loss: 0.6160
Epoch 10/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8754 - loss: 0.4942 - val_accuracy: 0.8500 - val_loss: 0.4836
Epoch 11/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8723 - loss: 0.6096 - val_accuracy: 0.8789 - val_loss: 0.3954
Epoch 12/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8601 - loss: 0.7603 - val_accuracy: 0.8900 - val_loss: 0.3479
Epoch 13/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8676 - loss: 0.6043 - val_accuracy: 0.8925 - val_loss: 0.4881
Epoch 14/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8720 - loss: 0.4776 - val_accuracy: 0.8925 - val_loss: 0.3183
Epoch 15/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8707 - loss: 0.5267 - val_accuracy: 0.7359 - val_loss: 1.2318
Epoch 16/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8673 - loss: 0.5499 - val_accuracy: 0.8626 - val_loss: 1.1469
Epoch 17/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8666 - loss: 0.7279 - val_accuracy: 0.8829 - val_loss: 0.3907
Epoch 18/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8773 - loss: 0.4485 - val_accuracy: 0.8824 - val_loss: 0.4368
Epoch 19/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8612 - loss: 0.7070 - val_accuracy: 0.8849 - val_loss: 0.6319
Epoch 20/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8686 - loss: 0.7124 - val_accuracy: 0.8941 - val_loss: 0.3985
Epoch 21/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8780 - loss: 0.4805 - val_accuracy: 0.8814 - val_loss: 0.9544
Epoch 22/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8699 - loss: 0.5804 - val_accuracy: 0.8890 - val_loss: 0.6362
Epoch 23/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8696 - loss: 0.5542 - val_accuracy: 0.8834 - val_loss: 0.5726
Epoch 24/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8753 - loss: 0.4409 - val_accuracy: 0.8824 - val_loss: 0.4664
Epoch 25/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8766 - loss: 0.4260 - val_accuracy: 0.8925 - val_loss: 0.3854
Epoch 26/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8756 - loss: 0.4729 - val_accuracy: 0.8870 - val_loss: 0.3773
Epoch 27/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8726 - loss: 0.4891 - val_accuracy: 0.8784 - val_loss: 0.4239
Epoch 28/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8786 - loss: 0.4032 - val_accuracy: 0.8875 - val_loss: 0.3644
Epoch 29/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8749 - loss: 0.4484 - val_accuracy: 0.8895 - val_loss: 0.3634
Epoch 30/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8775 - loss: 0.4493 - val_accuracy: 0.8951 - val_loss: 0.3155
Epoch 31/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8756 - loss: 0.4316 - val_accuracy: 0.8738 - val_loss: 0.4402
Epoch 32/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8772 - loss: 0.4971 - val_accuracy: 0.8839 - val_loss: 0.3435
Epoch 33/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8745 - loss: 0.5056 - val_accuracy: 0.8966 - val_loss: 0.3438
Epoch 34/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8787 - loss: 0.4074 - val_accuracy: 0.8880 - val_loss: 0.3125
Epoch 35/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8748 - loss: 0.4797 - val_accuracy: 0.8748 - val_loss: 0.3709
Epoch 36/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8720 - loss: 0.4449 - val_accuracy: 0.8870 - val_loss: 0.6343
Epoch 37/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8778 - loss: 0.4767 - val_accuracy: 0.8885 - val_loss: 0.4586
Epoch 38/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8724 - loss: 0.4986 - val_accuracy: 0.8981 - val_loss: 0.3355
Epoch 39/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8735 - loss: 0.4634 - val_accuracy: 0.8784 - val_loss: 0.6633
Epoch 40/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8790 - loss: 0.5938 - val_accuracy: 0.8920 - val_loss: 0.4042
Epoch 41/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8762 - loss: 0.4411 - val_accuracy: 0.8905 - val_loss: 0.3719
Epoch 42/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8790 - loss: 0.3931 - val_accuracy: 0.8849 - val_loss: 0.4940
Epoch 43/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8772 - loss: 0.4973 - val_accuracy: 0.8561 - val_loss: 1.8408
Epoch 44/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8823 - loss: 0.4281 - val_accuracy: 0.8870 - val_loss: 0.3350
Epoch 45/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8773 - loss: 0.4218 - val_accuracy: 0.8875 - val_loss: 0.5517
Epoch 46/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8752 - loss: 0.4893 - val_accuracy: 0.8834 - val_loss: 0.3656
Epoch 47/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8778 - loss: 0.3830 - val_accuracy: 0.8991 - val_loss: 0.2999
Epoch 48/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8783 - loss: 0.3963 - val_accuracy: 0.8789 - val_loss: 0.5207
Epoch 49/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8809 - loss: 0.4708 - val_accuracy: 0.8925 - val_loss: 0.2917
Epoch 50/50
247/247 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8806 - loss: 0.4230 - val_accuracy: 0.8910 - val_loss: 0.3165

['/mnt/c/Office 2019/DS_PW/DL_Practice/Shoppers Purchasing Intention/Notebook/shoppers_model.pkl']

In [19]:
y_pred =model.predict(X_test)

78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [20]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, (y_pred > 0.5).astype(int))
accuracy

0.878345498783455